name: Test

on:  
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:

          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: obiwan@example.com,yoda@example.com
          from: Luke Skywalker # <user@example.com>
          body: Build job of ${{github.repository}} completed successfully!
          cc: kyloren@example.com,leia@example.com
